<script setup lang="ts">
import { z } from 'zod'
import type { FormSubmitEvent } from '@nuxt/ui'

definePageMeta({
  layout: false
})

const { exchangeCode, isAuthenticated, isLoading, restoreSession } = useAuth()
const toast = useToast()

const schema = z.object({
  code: z.string().trim().min(1, 'Browser code is required')
})

type Schema = z.output<typeof schema>

const state = reactive({
  code: ''
})
const submitting = ref(false)

onMounted(async () => {
  await restoreSession()
  if (isAuthenticated.value) {
    await navigateTo('/dashboard')
  }
})

async function onSubmit(event: FormSubmitEvent<Schema>) {
  submitting.value = true
  const result = await exchangeCode(event.data.code)
  state.code = ''
  submitting.value = false

  if (result === 'success') {
    toast.add({
      title: 'Signed in',
      description: 'The browser session is active',
      color: 'success',
      icon: 'i-lucide-circle-check'
    })
    await navigateTo('/dashboard')
    return
  }

  if (result === 'invalid-code') {
    toast.add({
      title: 'Unable to sign in',
      description: 'The browser code is invalid, expired, or already used',
      color: 'error',
      icon: 'i-lucide-circle-alert'
    })
    return
  }

  toast.add({
    title: 'Unable to sign in',
    description: 'The server could not complete the sign-in request',
    color: 'error',
    icon: 'i-lucide-circle-alert'
  })
}
</script>

<template>
  <UApp>
    <div class="min-h-screen flex items-center justify-center bg-default p-4">
      <div v-if="isLoading" class="flex items-center justify-center" aria-label="Checking session">
        <UIcon name="i-lucide-loader-circle" class="size-8 animate-spin text-primary" />
      </div>

      <UCard v-else class="w-full max-w-md">
        <template #header>
          <div class="flex flex-col items-center gap-4">
            <div class="flex items-center gap-2">
              <UIcon name="i-lucide-server" class="size-10 text-primary" />
              <h1 class="text-2xl font-bold">TDNS Admin</h1>
            </div>
            <p class="text-muted text-center">
              Enter a short-lived browser code generated by the TDNS CLI
            </p>
          </div>
        </template>

        <UForm :schema="schema" :state="state" class="space-y-4" @submit="onSubmit">
          <UFormField name="code" label="Browser code">
            <UTextarea
              v-model="state.code"
              autocomplete="one-time-code"
              placeholder="Paste the browser code"
              :rows="4"
              autoresize
            />
          </UFormField>

          <UButton
            type="submit"
            block
            :loading="submitting"
            :disabled="submitting"
            icon="i-lucide-log-in"
          >
            Sign in
          </UButton>
        </UForm>

        <template #footer>
          <p class="text-sm text-muted text-center">
            Generate a code with <code>tdns adm browser-code</code>
          </p>
        </template>
      </UCard>
    </div>
  </UApp>
</template>
