package cmd

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestRenderRootManPage(t *testing.T) {
	t.Setenv("SOURCE_DATE_EPOCH", "1786233600")

	var output bytes.Buffer
	if err := renderRootManPage(rootCmd, manHeader(), &output); err != nil {
		t.Fatalf("render root manual page: %v", err)
	}

	page := output.String()
	for _, expected := range []string{
		`.TH "TDNS" "1" "Aug 2026"`,
		`TDNS Manual`,
		`.SH NAME`,
		`.SH SYNOPSIS`,
		`.SH OPTIONS`,
		`tdns-serve(1)`,
		`tdns-man(1)`,
	} {
		if !strings.Contains(page, expected) {
			t.Errorf("manual page is missing %q", expected)
		}
	}
	if strings.Contains(page, "Auto generated by spf13/cobra") {
		t.Error("manual page contains Cobra's non-project autogeneration marker")
	}
}

func TestGenerateConsolidatedManPages(t *testing.T) {
	t.Setenv("SOURCE_DATE_EPOCH", "1786233600")
	outputDir := t.TempDir()

	if err := generateManTree(rootCmd, manHeader(), outputDir, false); err != nil {
		t.Fatalf("generate manual page tree: %v", err)
	}

	for _, name := range []string{
		"tdns.1",
		"tdns-adm.1",
		"tdns-config.1",
		"tdns-man.1",
		"tdns-serve.1",
	} {
		contents, err := os.ReadFile(filepath.Join(outputDir, name))
		if err != nil {
			t.Errorf("read generated page %s: %v", name, err)
			continue
		}
		if len(contents) == 0 {
			t.Errorf("generated page %s is empty", name)
		}
	}

	if _, err := os.Stat(filepath.Join(outputDir, "tdns-adm-start-stub-resolver.1")); !os.IsNotExist(err) {
		t.Errorf("nested subcommand has a separate manual page: %v", err)
	}
	admPage, err := os.ReadFile(filepath.Join(outputDir, "tdns-adm.1"))
	if err != nil {
		t.Fatalf("read consolidated adm page: %v", err)
	}
	for _, expected := range []string{
		`.TH "TDNS-ADM" "1" "Aug 2026"`,
		".SH SUBCOMMANDS",
		"tdns-adm-password-set",
		"tdns-adm-start-stub-resolver",
		"tdns-adm-stop-static-response",
	} {
		if !strings.Contains(string(admPage), expected) {
			t.Errorf("consolidated adm page is missing %q", expected)
		}
	}
	if strings.Contains(string(admPage), "tdns-adm-start-stub-resolver(1)") {
		t.Error("consolidated adm page links to a manual page that is no longer generated")
	}
	if count := strings.Count(string(admPage), ".TH "); count != 1 {
		t.Errorf("consolidated adm page contains %d document headers, want 1", count)
	}

	if err := generateManTree(rootCmd, manHeader(), outputDir, false); err == nil || !strings.Contains(err.Error(), "already exists") {
		t.Fatalf("second generation error = %v, want an existing-page error", err)
	}
	if err := generateManTree(rootCmd, manHeader(), outputDir, true); err != nil {
		t.Fatalf("force manual page generation: %v", err)
	}
}

func TestManPageGenerationIsReproducible(t *testing.T) {
	t.Setenv("SOURCE_DATE_EPOCH", "1786233600")

	render := func() string {
		t.Helper()
		var output bytes.Buffer
		if err := renderRootManPage(rootCmd, manHeader(), &output); err != nil {
			t.Fatalf("render root manual page: %v", err)
		}
		return output.String()
	}

	first := render()
	time.Sleep(time.Millisecond)
	second := render()
	if first != second {
		t.Error("manual page output changed with a fixed SOURCE_DATE_EPOCH")
	}
}
