package api

import _ "embed"

// openAPISpec is generated by tools/generate_api.sh.
//
//go:embed openapi.yaml
var openAPISpec []byte

// OpenAPISpec returns a copy of the generated OpenAPI 3.0 contract.
func OpenAPISpec() []byte {
	return append([]byte(nil), openAPISpec...)
}
